# Generated by Django 4.2.5 on 2023-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
