# Generated by Django 4.2.5 on 2023-09-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_job_apply_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
    ]
